pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/your-username/data-engineering-projects.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t spark-data-pipeline .'
            }
        }

        stage('Run Spark Job') {
            steps {
                sh 'docker run --rm spark-data-pipeline'
            }
        }
    }

    post {
        success {
            echo 'Pipeline executed successfully'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}
